### ISSUE TITLE
Add plugin/theme info to the wiki.

### ISSUE THREAD

**Issue by wizonesolutions** [fish-shell/oh-my-fish#460]
oh-my-zsh does this for themes at least, and it's really nice for seeing things at a glance https://github.com/robbyrussell/oh-my-zsh/wiki/themes

Alternatively, maybe you could hook into `fish_config` (if possible) to make it possible to go through them there.

**Comment by bucaran** [comment]
> oh-my-zsh does this for themes at least, and it's really nice for seeing things at a glance https://github.com/robbyrussell/oh-my-zsh/wiki/themes

:+1: 

> Alternatively, maybe you could hook into fish_config (if possible) to make it possible to go through them there.

What do you mean? We have something better, [_theme_](https://github.com/bpinto/oh-my-fish/tree/master/plugins/theme).

**Comment by wizonesolutions** [comment]
@bucaran true, I probably noticed that later. What it lacks is a quick overview of all of them (because the names don't really tell me what theme I might want to try. well, except maybe `fishy-drupal` :D)

**Comment by bucaran** [comment]
We should definitely have a page to show off all the available themes and hooking into `fish_config`, it's a very good idea.

**Comment by alexbooker** [comment]
I am new to `fish` and consequently, `oh-my-fish`, and this is one of the first things I looked for. It would be awesome to have.

@bucaran, this is issue is labelled as `PR welcome`. Do you want a PR (adding `themes.md`) or would you like someone to update the [Wiki](https://github.com/bpinto/oh-my-fish/wiki)?

**Comment by bucaran** [comment]
Either works well. Which you find more convenient would be very much appreciated! :smile:

**Comment by bucaran** [comment]
Still up to you, but giving it a second thought, a theme gallery page in the Wiki would be more convenient and easier to manage too.

**Comment by bpinto** [comment]
@alexbooker That would be great!

**Comment by bpinto** [comment]
Fixed with #512
