### ISSUE TITLE
`omf install` fails on second user to run it on the same host

### ISSUE THREAD

**Issue by Slotos** [fish-shell/oh-my-fish#479]
Currently, if two users attempt to run `omf install` on the same host without clearing /tmp in between, the second one will fail with warnings:

    Installing theme... An error occurred while redirecting file '/tmp/oh-my-fish.clone.log'
    open: Permission denied

    Installing robbyrussell... An error occurred while redirecting file '/tmp/oh-my-fish.clone.log'
    open: Permission denied

To prevent this omf should use `tempfile`, `mktemp` or similar faculty in order to create unique filenames.

**Comment by bpinto** [comment]
Fixed with #512
