### ISSUE TITLE
Theme contribution: tomita

### ISSUE THREAD

**Issue by daveyarwood** [fish-shell/oh-my-fish#487]
https://github.com/daveyarwood/tomita

**Comment by bpinto** [comment]
Could you follow this [guide](https://github.com/fish-shell/oh-my-fish/blob/master/CONTRIBUTING.md) for the package?

**Comment by bucaran** [comment]
We got tomita
https://github.com/fish-shell/oh-my-fish/blob/master/db/themes/tomita
