### ISSUE TITLE
Create a `omf uninstall` command

### ISSUE THREAD

**Issue by douglascamata** [fish-shell/oh-my-fish#488]
It would be nice to be able to uninstall plugins. I was migrating from the old oh-my-fish to this new one and tried to install an plugin named `rake`, which does not exist anymore. Now even with `Plugin "rake"`removed from my fish config file it still tries to install it.

**Comment by bobthecow** [comment]
Does the issue persist if you open a new shell?

**Comment by douglascamata** [comment]
It persisted with new shells. I was so mad at it that I reinstalled oh-my-fish completely and then it worked.

**Comment by bobthecow** [comment]
If this is the case, it's a bug. We don't need `uninstall`, we just need it to work as expected :)

**Comment by bpinto** [comment]
Fixed with #512
