### ISSUE TITLE
omf install plugins ask for github login

### ISSUE THREAD

**Issue by gblmarquez** [fish-shell/oh-my-fish#489]
Guys I`m new on OSX world so take it easy :)

I`m having some trouble when I run the omf install some plugins ask`s for github login, as the screen shot bellow.

![screen shot 2015-06-23 at 10 35 47 pm](https://cloud.githubusercontent.com/assets/367279/8321030/39511706-19f8-11e5-9f06-7589dad94363.png)

There are any workaround or fix for this issue?

**Comment by dreamspy** [comment]
I get the same when I try to install the git plugin:

![image](https://cloud.githubusercontent.com/assets/4160163/8321336/095cdbda-1a15-11e5-9675-830adb6b192c.png)

**Comment by dreamspy** [comment]
Maybe because there is not git plugin for fish? (solves my case at least)

**Comment by gblmarquez** [comment]
@dreamspy all the plugins that not use the git are installed normally.

maybe someone figures out a workaround.

**Comment by dreamspy** [comment]
Yeah it seems that completion is enabled by default for git.

**Comment by bobthecow** [comment]
None of those plugins exist, so it won't be able to install them. `omf` should definitely have better error handling in that case. Why are you trying to install plugins that don't exist, though? :)

Here's the list of plugins `omf` supports: https://github.com/oh-my-fish?utf8=✓&query=plugin-

**Comment by dreamspy** [comment]
I saw a mention of them at a guide for setting up fish and oh-my-fish.
Probably some mixup in that turorial.
ᐧ

Kær Kveðja / Kind Regards
Frímann Kjerúlf Björnsson
GSM: +354 822-3685

**Comment by gblmarquez** [comment]
@bobthecow thanks for the insight!

**Comment by bobthecow** [comment]
Let's leave the issue open until we sort out better 404 handling. That way at least other people with the same problem will see the open issue :)

**Comment by simonbcn** [comment]
I have a problem installing `better-alias`:
![error-fish](https://cloud.githubusercontent.com/assets/428231/9126047/4b1747bc-3ca8-11e5-8ea9-9c984f84c562.jpg)

The url of the git repository is wrong.

**Comment by bpinto** [comment]
@simonbcn Could you try reloading your shell?

**Comment by simonbcn** [comment]
ok, now it works. :+1:

**Comment by bpinto** [comment]
Cool!
