### ISSUE TITLE
Gradle plugin

### ISSUE THREAD

**Issue by hanny24** [fish-shell/oh-my-fish#494]
Another plugin of mine: https://github.com/hanny24/gradle-fish 
Provides tab complete for options and task names.

**Comment by bpinto** [comment]
Could you follow this [guide](https://github.com/fish-shell/oh-my-fish/blob/master/CONTRIBUTING.md) for the package?

**Comment by bpinto** [comment]
By the way, you could add it directly to https://github.com/fish-shell/fish-shell
