### ISSUE TITLE
Plugin for boot2docker on mac

### ISSUE THREAD

**Issue by creeonix** [fish-shell/oh-my-fish#500]
Very simple wrapper for `docker` command on OSX to launch boot2dcoker VM and export its environment vars properly.

if VM is not running it starts VM with `boot2docker up`, however, it won't run `boot2docker init` if VM container is not initialized.

It will evals `boot2docker shellinit` before any `docker` command  to make sure that environment variables are set properly.

Plugin can be found here: https://github.com/creeonix/fish-boot2docker

**Comment by bpinto** [comment]
@creeonix boot2docker is no longer "supported", what do you think about supporting the new tool?

**Comment by creeonix** [comment]
What do you mean? https://github.com/boot2docker/boot2docker last update 5h ago...

**Comment by bpinto** [comment]
http://blog.docker.com/2015/08/docker-toolbox/

**Comment by creeonix** [comment]
Cool, thanks. Will try that out.
