### ISSUE TITLE
United States of the Fish or the Fellowship of the Fish

### ISSUE THREAD

**Issue by bucaran** [fish-shell/oh-my-fish#507]
:bowtie: Dear everyone,

I will be updating this issue over the following hours describing the specific plan of action, but after a long discussion with @bpinto we have finally decided it is for the best to reunite and merge [Wahoo](https://github.com/wa/wahoo/) and [Oh My Fish](https://github.com/oh-my-fish/oh-my-fish) :tada: 

We will help everyone during the transition and ensure nothing breaks during the process.

**Comment by bobthecow** [comment]
:cool:

**Comment by bpinto** [comment]
:tada: :tada:

**Comment by gretel** [comment]
:four_leaf_clover: :wedding: :ring: :bride_with_veil: :two_men_holding_hands: :two_women_holding_hands: :two_hearts:

**Comment by jonscottclark** [comment]
Congrats both of you, I am super glad that you were able to reach an agreement and combine your powers! :)

**Comment by bucaran** [comment]
[This is](https://github.com/fish-shell/oh-my-fish/pull/512) the relevant PR.

## Regarding Organization Teams

Now it's possible to give members the ability to create and manage their own repos, so creating a team for each new package is no longer needed. If you want to collaborate to Oh My Fish! send us a message and we will add you to the members group.

> Notice that in the new architecture, users can host their packages and themes anywhere, given you have a git URL. Having said that, we would like to encourage people to join the [organization](https://github.com/oh-my-fish) and host their packages or themes with us.

**Comment by bpinto** [comment]
@jonscottclark :+1: 

It was merged and now closed! :tada:
