### ISSUE TITLE
Paths do not exist upon installation.

### ISSUE THREAD

**Issue by nesl247** [fish-shell/oh-my-fish#524]
After installing oh-my-fish, the following is the output when doing a `source ~/.config/fish/config.fish`.

```
source: Error encountered while sourcing file '/Users/harrison/.local/share/omf/lib/lib.fish':
source: No such file or directory
source: Error encountered while sourcing file '/Users/harrison/.local/share/omf/lib/git/git.fish':
source: No such file or directory
source: Error encountered while sourcing file '/Users/harrison/.dotfiles/omf/omf.fish':
source: No such file or directory
source: Error encountered while sourcing file '/Users/harrison/.local/share/omf/events.fish':
source: No such file or directory
source: Error encountered while sourcing file '/Users/harrison/.dotfiles/init.fish':
source: No such file or directory
```

There shouldn't be any errors after installing.

**Comment by bpinto** [comment]
ping @bucaran

**Comment by bobthecow** [comment]
@nesl247 It looks like your install wasn't successful at all. What installation method did you use?

**Comment by nesl247** [comment]
I ran the auto installer via sh pipe. I did the upgrade initially, and then I did `omf destroy` and reran the installer and had the same results.

**Comment by bpinto** [comment]
Could you show me the output of the following:

```
$ type source
$ fish -v
```

**Comment by nesl247** [comment]
Here you go.

```
➜  ~ type source
source is a builtin
➜  ~ fish -v
fish, version 2.2.0-204-ge0e7325
```

**Comment by bpinto** [comment]
Do you have anything in your `/Users/harrison/.local/share/omf/` folder?

If you would like to join gitter, we are online.

**Comment by nesl247** [comment]
Yep, it's a git repository and no changes have been made. I'll have to check it out later with you guys.

**Comment by bpinto** [comment]
@nesl247 What was the problem?

**Comment by nesl247** [comment]
No idea, I didn't solve the issue.

**Comment by bpinto** [comment]
Could it be permission error?

**Comment by nesl247** [comment]
The issue is omf is literally trying to source files that don't exist... Either checks if the file exist need to be made, or create empty files on install.

**Comment by bobthecow** [comment]
It's a botched install. Those files are created on install.

**Comment by bucaran** [comment]
@nesl247 What is your OS? Maybe some OS throw an error if you try to source files that do not exist. Because I never got this error before.

**Comment by bpinto** [comment]
I reproduced it, just call source on the init file and you would see it.

**Comment by bucaran** [comment]
Yes, fixed already.
