### ISSUE TITLE
OMF_CUSTOM does not seem to load dotfiles

### ISSUE THREAD

**Issue by dan-c-underwood** [fish-shell/oh-my-fish#527]
I was unable to get omf to successfully load custom dotfiles pointed to via the OMF_CUSTOM path. Both setting it to be a specific file or a directory containing a dotfile had no effect.

**Comment by bpinto** [comment]
How were these custom files named?

**Comment by dan-c-underwood** [comment]
Probably not the way that they should have been!

I think I tried a variety including:

* my.fish
* config.fish

**Comment by bobthecow** [comment]
it only loads `init.fish`, not all files in OMF_CUSTOM. you can source the files yourself in `$OMF_CUSTOM/init.fish`, or you can make them packages (e.g. `$OMF_CUSTOM/pkg/my/my.fish`) to get them automatically sourced.

**Comment by dan-c-underwood** [comment]
It might be worthwhile linking to that (found it in the FAQ) from the README page as currently that section isn't really that clear on its own!

**Comment by bpinto** [comment]
@dan-c-underwood I agree, could you open a PR?

@bobthecow any reason not to load every `*.fish` file?

**Comment by dan-c-underwood** [comment]
Sure! I'll get that done tomorrow.

**Comment by bucaran** [comment]
> it only loads `init.fish`, not all files in OMF_CUSTOM. you can source the files yourself...

This is the intended behavior and if it's not really obvious, then we should add a section in the FAQ for that or...

> It might be worthwhile linking to that (found it in the FAQ) from the README page as currently that section isn't really that clear on its own!

If you can improve the README, sure give it a shot :smile: , but I would prefer to add a section in the FAQ.
