### ISSUE TITLE
Where to add custom aliases

### ISSUE THREAD

**Issue by bronzehedwick** [fish-shell/oh-my-fish#540]
Maybe I'm just not seeing the obvious, but I've been poking around for a bit with this new structure, and can't seem to figure out where I put my custom aliases. Do I need to make a new package locally? I used to be able to put them in `~/.oh-my-fish/custom/my-aliases.load`.

**Comment by bucaran** [comment]
So, there are no more `.load` files. Here are a few ways in the new architecture:

+ Inside `$OMF_CONFIG/init.fish`
+ Create a custom plugin `omf new plugin <your name>`
  + Inside that file add:
  ```fish
    function init --on-event init_<your name>
      # create your aliases
    end
  ```

**Comment by bronzehedwick** [comment]
great, thanks!
