### ISSUE TITLE
autocomplete slowness

### ISSUE THREAD

**Issue by bpinto** [fish-shell/oh-my-fish#568]
When typing `omf` commands, sometimes the shell becomes "slow". I type some characters but it doesn't show on the shell.

Example `omf in` before I complete `install`, it is slow as if it was processing something. This seems to me a problem with autocomplete. Has anyone noticed a similar issue?

**Comment by derekstavis** [comment]
I'm experiencing the same issue. The first problem is that we do completion just after typing `omf i`:

    complete -c omf -n "__omf.opt_is i install"       -a (printf "%s " (omf.list_db_packages))

The second problem is that fish is computing the completions just after typing the subcommand, instead of just doing it when you <kbd>TAB</kbd>.

**Comment by bucaran** [comment]
@bpinto I can't reproduce it here :confused:

**Comment by bpinto** [comment]
Luck you!! :)

I'll have to test it, but it does seem related to the short sub command names.

**Comment by bucaran** [comment]
Mmm. If you manage to reproduce it let me know how it goes.

**Comment by bpinto** [comment]
Can't find anything... Closing then.
