### ISSUE TITLE
Duplicated agnoster theme

### ISSUE THREAD

**Issue by derekstavis** [fish-shell/oh-my-fish#571]
I've been using `agnoster copy`, since it's the same package as `agnoster` before wahoo merge. Also, according to plugin/theme naming scheme there shouldn't be spaces in names.

**Comment by bucaran** [comment]
Can you check which one is the most appropriate one and discard the other? Then, update the registry.

**Comment by derekstavis** [comment]
The most appropriate is `agnoster copy`, which is what we had before the merge. It's funny how it got the `copy` suffix, even if it was the first one to appear.
