### ISSUE TITLE
please stop hosing everything

### ISSUE THREAD

**Issue by zacheryph** [fish-shell/oh-my-fish#577]
a while back i attempted to `omf update` and it hosed everything.  turns out the location omf installs to was different, the configuration file totally changed.  causing me to have to wipe everything and reinstall all plugins.

now i try updating and master was force pushed to preventing `omf update` from working.

should we just assume `omf update` will not work and forget about the command? or will this stuff be stable sooner rather than later?

**Comment by derekstavis** [comment]
I'm sorry for your issue. I've experienced the same. You can always do a clean install to ensure your environment is clean. But before, be sure to remove `~/.oh-my-fish` and backup `~/.config/fish/config.fish` and your custom files.
