### ISSUE TITLE
omf install does not list uninstalled packages

### ISSUE THREAD

**Issue by bucaran** [fish-shell/oh-my-fish#578]

**Comment by bpinto** [comment]
Mind you add a description? I don't understand the bug.

**Comment by bucaran** [comment]
`omf install` should show the packages that you can install if passed without arguments. How can you discover packages now?

**Comment by bpinto** [comment]
This has been discussed here: https://github.com/fish-shell/oh-my-fish/pull/564#issuecomment-136150807

`omf install` should not display the list of packages. If you read `omf install` as plain english, you would not expect it to return a list of packages.

@bobthecow suggested using `list --available` on gitter. And I think that's a good solution.
IMO, we should change the default behaviour of `list` to the following:

```
  list --available: only list available packages
  list --installed: only list installed packages
  list: list installed and available packages
```

The output from `list` could be either of those:
```
  Installed:
    brew  bundler
  Available:
    rbenv nvm
```

or 

```
    brew*  bundler*    rbenv nvm
```

**Comment by bucaran** [comment]
I would prefer an even simpler solution, where the idea of themes, plugins, bundles and all that stuff is no longer necessary. We could go with only packages.

**Comment by bpinto** [comment]
Eager to hear what you have in your mind.

**Comment by bucaran** [comment]
Absolutely.

**Comment by derekstavis** [comment]
I like the idea of treating everything as packages. :+1:

**Comment by derekstavis** [comment]
What we could have is some kind of categorization of plugins. I imagined some common use cases:

* Polyfills -> `plugin-pbcopy`, `plugin-sublime`, ...
* Completions -> `apt-get`, `pacman`, `yum`, `dnf`, ...
* Themes -> `default`, `agnoster`, `bobthefish`, ...

**Comment by bpinto** [comment]
Completions are better of pushed to `fish-shell` directly. So we are back to plugins and themes? :D

**Comment by bucaran** [comment]
> Completions are better of pushed to fish-shell 

Correct.

**Comment by derekstavis** [comment]
I didn't know they accepted completions *__*

**Comment by bpinto** [comment]
So apparently everyone agree this is unrelated to `omf install`.
