### ISSUE TITLE
Maven Completion

### ISSUE THREAD

**Issue by jschneider** [fish-shell/oh-my-fish#585]
I have created a maven completion file: 
Any interest to combine that with oh-my-fish?

https://github.com/jschneider/fish-maven-completion

**Comment by bobthecow** [comment]
Fish core is actually really good about including completions, and that improves things for everyone whether they use omf or not. Try there first? If that doesn't work, come back here :)

**Comment by bucaran** [comment]
@jschneider In the mean time, you can put your completions inside `$OMF_PATH/completions` and omf will correctly read as there is support for that.
