### ISSUE TITLE
What if Oh My Fish! had a different name?

### ISSUE THREAD

**Issue by bucaran** [fish-shell/oh-my-fish#591]
Somedays I like OMF, somedays I don't find it very amusing. Just as a mental experiment, if Oh My Fish! were to change its name, which name would you like?

Here are some options:

+ Fisher (Bobby Fisher reference?)
+ Stingray
+ Blue
+ Triton
+ Poseidon
+ Pez
+ Mar
+ Whirpool

Feel free to comment on this suggestions or provide your own. If you instead like Oh My Fish! just the way it is, please share why do you feel this way.

Best

**Comment by scorphus** [comment]
:-1:

Oh My Fish! FTW (the F stands for *Forever*)

**Comment by derekstavis** [comment]
:-1:

**Comment by bpinto** [comment]
Totally unrelated to the repo. Do not open an issue like this before talking to the internal team.

**Comment by bucaran** [comment]
I disagree. If you don't want to post here don't.
